# .streamlit/config.toml

[theme]
base = "dark"  # or "light"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "monospace"  # or "serif", "monospace"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

